version: 'latest'

services:
  golang:
    build:
      context: ./go_api/
    volumes:
      - ./go_api:/usr/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
  python:
    build:
      context: ./python_api/
    volumes:
      - ./python_api:/usr/app/
    ports:
      - "5000:5000"
    networks:
      - dev-net
    env_file:
      - .env
    environment:
      FLASK_APP: app.py
