version: 'latest'

services:
  golang:
    build:
      context: ./go_api/
    ports:
      - "8000:8000"
    env_file:
      - .env
  python:
    build:
      context: ./python_api/
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      FLASK_APP: app.py
